web:
  build: .
  volumes:
    - .:/app
  ports:
    - "9990:9292"
  links:
    - redis
  environment:
    REDIS_PROVIDER: 'redis://redis:6379/'
redis:
  image: redis:alpine
  ports:
    - "6379:6379"
